apiVersion: v1
kind: Service
metadata:
  name: atena-postgres
  namespace: atena
spec:
  ports:
    - port: 5432
  selector:
    app: atena-postgres
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: atena-postgres
  namespace: atena
spec:
  selector:
    matchLabels:
      app: atena-postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: atena-postgres
    spec:
      containers:
        - image: postgres:15
          name: postgres
          env:
            - name: POSTGRES_DB
              value: atena
            - name: POSTGRES_USER
              value: atena
            - name: POSTGRES_PASSWORD
              value: password
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
