apiVersion: v1
kind: Service
metadata:
  name: atena-django
  namespace: atena
spec:
  selector:
    app: atena-django
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
